config/routes.rb
CalculatorApp::Application.routes.draw do

  devise_for :users
  root 'client#index'
  get 'api_calculator' => 'client#index'
  put 'calculator' => 'calculator#update'
  namespace :api do
    put 'calculator_update'  => 'calculator#update'
    post 'calculator_create' => 'calculator#create'
  end

end

app/models/calculator.rb
#Models calculator
class Calculator < ActiveRecord::Base
belongs_to :user
  def +(input)
    self.state += input
    self.save
  end

  def -(input)
    self.state -= input
    self.save
  end
  def *(input)
    self.state *= input
    self.save
  end
  def /(input)
    self.state /= input
    self.save
  end
  def abs
    self.state = self.state.abs
    self.save
  end
  def neg
    self.state = self.state*-1
    self.save
  end
  def sqrt
    begin
      self.state = Math.sqrt self.state
        self.save
    rescue
      puts "Returns Complex number"
    end

  end
  def sqr
    self.state = self.state**2
    self.save
  end
  def cube
    self.state = self.state**3
    self.save
  end
  def cubert
    self.state = Math.cbrt self.state
    self.save
  end
  def cancel
    self.state = 0
    self.save
  end
end

app/models/operations.rb
#Defines operations and performs delegation
class Operations
  attr_reader :operator,:operand
  def initialize operation,operand=0
    @operator = operation
    @operand = operand
  end
  def operate calculator
    case @operator
      when 'add'
        calculator+(@operand)
      when 'sub'
        calculator-(@operand)
      when 'multiply'
        calculator*(@operand)
      when 'divide'
        calculator/(@operand)
      when 'sqr'
        calculator.sqr
      when 'sqrt'
        calculator.sqrt
      when 'cube'
        calculator.cube
      when 'cubert'
        calculator.cubert
      when 'abs'
        calculator.abs
      when 'cancel'
         calculator.cancel
      when 'neg'
        calculator.neg
    end
  end
  def ==(other)
      return true if self.equal?(other)
      return false if other.nil?
      return false if other.class != self.class
      @operator == other.operator && @operand == other.operand
  end

  def hash
      37*(@operator.hash)
  end

  def eql? other
    self == other
  end
end

app/models/parser.rb
#parses the given string and returns an operation
class Parser
  def parse input
    input = input.split
    @operator,@operand = input[0], input[1].to_f
    Operations.new(@operator,@operand)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :calculator
end

app/controllers/Api/calculator_controller.rb
#Performs Calculator Operations
class Api::CalculatorController < ApiController
  def create
     unless current_user.calculator
      current_user.calculator=Calculator.create({:state => 0, :user => current_user})
      head 201
     else
       head: ok
     end
  end

    def update
      input = params[:command]
      if (current_user.calculator.nil?)
        head 404
      else
        calculator = current_user.calculator
        parser = Parser.new
        operation = parser.parse(input)
        operation.operate(calculator)
        render :json => {:state => calculator.state}
      end
    end
  end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/calculator_controller.rb
#Controller for Calculator
class CalculatorController<ApplicationController
  def update
        calculator = find_or_create_with_default
        parser = Parser.new
        input = params[:command]
        operation = parser.parse(input)
        operation.operate(calculator)
        @state = Calculator.last.state
    end

  def create
    @state = find_or_create_with_default.state
  end

private
  def find_or_create_with_default
    Calculator.last||Calculator.new({:state => 0})
  end

end

app/controllers/client_controller.rb
#Performs Calculator Operations
class ClientController < ApplicationController
def index

end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculator/_form.html.erb
<%= form_tag(calculator_path, method: "put") do %>

    <%= label_tag(:command, "Input:") %>

    <%= text_field_tag(:command) %>

    <%= submit_tag("Calculate") %>

<% end %>

app/views/calculator/_state.html.erb
Value: <%= @state %>

app/views/calculator/create.html.erb
<%= render :partial =>"form"%>

<%= render :partial =>"state"%>

app/views/calculator/update.html.erb
<%= render partial: 'form' %>
<%= render partial: 'state' %>

app/views/client/_form.html.erb
<H3>Api Calculator</H3>
<input class="addCalculator" type="submit" value="Add Calculator">
<div class="calculatorsBody"></div>
<div id="templates" style="visibility: hidden">
<div class="calculator">
  Enter Command:
  <input type="text" class="command"/>
  <input type="button" class="submit" value="Submit"/>
  <H5>Result : </H5>
<div class="result"></div>
</div>


</div>

app/views/client/_state.html.erb
<div id="state"></div>

app/views/client/index.html.erb
<%= render partial: 'form' %>
<%= render partial: 'state' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculator App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
</body>
</html>